// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB9nXDhMNc-Lrew2Y9WHK6_9o04usuM9I',
    appId: '1:512381849230:web:8fbc1f5c278564b7cb03df',
    messagingSenderId: '512381849230',
    projectId: 'ship-it-ca92f',
    authDomain: 'ship-it-ca92f.firebaseapp.com',
    storageBucket: 'ship-it-ca92f.appspot.com',
    measurementId: 'G-Y83H3856QN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxLXlnOeQ57q9wSsKYZGAEulQrSCgo0Gs',
    appId: '1:512381849230:android:69d1c908bb5703b6cb03df',
    messagingSenderId: '512381849230',
    projectId: 'ship-it-ca92f',
    storageBucket: 'ship-it-ca92f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzpjSiI5pv1wmfoVRFWACrGqI4iJJ68fI',
    appId: '1:512381849230:ios:d96b15ff59453051cb03df',
    messagingSenderId: '512381849230',
    projectId: 'ship-it-ca92f',
    storageBucket: 'ship-it-ca92f.appspot.com',
    iosClientId: '512381849230-msukrj6q2bc307rl0qvif46f6a5kt9fa.apps.googleusercontent.com',
    iosBundleId: 'space.ship-it.ship-it',
  );
}
